# Generated by Django 5.0.8 on 2024-10-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={"verbose_name_plural": "About"},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"verbose_name_plural": "Education"},
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"verbose_name_plural": "Experience"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name_plural": "Service"},
        ),
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.ImageField(
                blank=True,
                default="portfolio_images/default.jpg",
                upload_to="portfolio_images/",
            ),
        ),
    ]
