# Generated by Django 5.0.8 on 2024-10-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_about_options_alter_education_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.ImageField(
                blank=True,
                default="portfolio_images/default.jpeg",
                upload_to="portfolio_images/",
            ),
        ),
    ]
